export const styles = {
  appViewport: { width: '100vw', backgroundColor: '#000', overflow: 'hidden', display: 'flex', flexDirection: 'column' },
  calcPage: { height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 1, background: 'radial-gradient(circle at center, #1a1a1a 0%, #000 100%)' },
  calcCard: { width: '100%', maxWidth: '400px', padding: '20px' },
  calcDisplay: { fontSize: '70px', color: '#8a9a8e', textAlign: 'right', padding: '40px 10px', minHeight: '160px' },
  calcGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px' },
  calcBtn: { aspectRatio: '1', borderRadius: '18px', border: 'none', backgroundColor: '#111', color: '#fff', fontSize: '24px' },
  opBtn: { backgroundColor: '#222', color: '#8a9a8e' },
  equalBtn: { backgroundColor: '#8a9a8e', color: '#000', fontWeight: 'bold' },
  chatPage: { height: '100%', display: 'flex', flexDirection: 'column', backgroundColor: '#050505', overflow: 'hidden' },
  chatHeader: { padding: '60px 24px 15px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #111', backgroundColor: '#0a0a0a' },
  statusDot: { width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#4ade80', marginRight: '10px', boxShadow: '0 0 10px #4ade80' },
  lockBtn: { background: 'none', border: 'none', color: '#8a9a8e', fontWeight: 'bold', fontSize: '16px' },
  messageList: { flex: 1, padding: '20px', paddingBottom: '100px', overflowY: 'auto', display: 'flex', flexDirection: 'column', WebkitOverflowScrolling: 'touch' },
  msgRow: { display: 'flex', marginBottom: '14px', width: '100%' },
  bubble: { padding: '12px 18px', borderRadius: '22px', maxWidth: '85%', fontSize: '16px' },
  inputArea: { padding: '15px 20px', paddingBottom: 'calc(15px + env(safe-area-inset-bottom))', display: 'flex', gap: '12px', backgroundColor: '#0a0a0a', borderTop: '1px solid #111', alignItems: 'center' },
  imgBtn: { background: 'none', border: 'none', fontSize: '22px', cursor: 'pointer', padding: '0 5px' },
  input: { flex: 1, padding: '14px 20px', borderRadius: '30px', border: 'none', backgroundColor: '#1a1a1a', color: '#fff', fontSize: '16px', outline: 'none' },
  sendBtn: { width: '48px', height: '48px', borderRadius: '50%', border: 'none', backgroundColor: '#8a9a8e', color: '#000' },
  downloadLink: { display: 'block', fontSize: '11px', textDecoration: 'none', marginTop: '8px', textAlign: 'center', fontWeight: 'bold', opacity: 0.8 }
};